/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <pthread.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif

JavaVM *gJavaVM;
jobject gJavaObj;
static volatile int gIsThreadExit = 0;

/*
 * Class:     Native
 * Method:    nativeInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Native_nativeInitialize
  (JNIEnv *, jobject);

/*
 * Class:     Native
 * Method:    nativeThreadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Native_nativeThreadStart
  (JNIEnv *, jobject);

/*
 * Class:     Native
 * Method:    nativeThreadStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Native_nativeThreadStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
